version: '3.8'

services:
  vulseek-release:
    image: ghcr.io/fuzzing-peach/vulseek:v0.25.8
    container_name: vulseek-release
    restart: unless-stopped
    ports:
      - "23001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vulseek_release_data:/etc/vulseek
      - docker_release_config:/root/.docker
      # scan runtime context
      - ${VULSEEK_SCAN_CONTEXT_HOST_PATH:-./vulseek-data}:/scan-context
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://vulseek:vulseek_dev_password@vulseek-postgres-dev:5432/vulseek
      - REDIS_URL=redis://vulseek-redis-dev:6379
      - ADVERTISE_ADDR=${ADVERTISE_ADDR:-127.0.0.1}
      - VULSEEK_SCAN_CONTEXT_HOST_PATH=${VULSEEK_SCAN_CONTEXT_HOST_PATH:-./vulseek-data}
    privileged: true
    networks:
      - vulseek-dev-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  vulseek_release_data:
  docker_release_config:

networks:
  vulseek-dev-network:
    external: true
