export type FileScopeCategory =
	| "runtime-code"
	| "test"
	| "fixture"
	| "documentation"
	| "example"
	| "configuration"
	| "generated"
	| "vendor"
	| "asset"
	| "unknown";

export type FileScopeAction = "include" | "exclude";

export type FileScopeClassification = {
	path: string;
	category: FileScopeCategory;
	action: FileScopeAction;
	reason: string;
};

export type ModuleScopeClassification = {
	category: FileScopeCategory;
	action: FileScopeAction;
	reason: string;
};

const codeExtensions = new Set([
	".c",
	".cc",
	".cpp",
	".cxx",
	".h",
	".hh",
	".hpp",
	".hxx",
	".m",
	".mm",
	".go",
	".rs",
	".java",
	".kt",
	".kts",
	".scala",
	".js",
	".jsx",
	".ts",
	".tsx",
	".mjs",
	".cjs",
	".py",
	".rb",
	".php",
	".cs",
	".swift",
	".erl",
	".ex",
	".exs",
	".lua",
	".pl",
	".pm",
	".sh",
	".bash",
	".zsh",
	".ps1",
	".sql",
]);

const documentationExtensions = new Set([
	".md",
	".mdx",
	".rst",
	".adoc",
	".txt",
	".markdown",
]);

const configurationExtensions = new Set([
	".json",
	".jsonc",
	".yaml",
	".yml",
	".toml",
	".ini",
	".cfg",
	".conf",
	".config",
	".xml",
	".lock",
	".sum",
	".mod",
	".cmake",
	".mk",
	".am",
	".in",
	".cmd",
	".bat",
]);

const assetExtensions = new Set([
	".png",
	".jpg",
	".jpeg",
	".gif",
	".svg",
	".ico",
	".webp",
	".avif",
	".pdf",
	".zip",
	".gz",
	".tar",
	".tgz",
	".xz",
	".map",
	".snap",
	".pem",
	".crt",
	".cer",
	".key",
]);

const generatedSegments = new Set([
	"node_modules",
	"vendor",
	"third_party",
	"third-party",
	"generated",
	"autogenerated",
	"gen",
	"dist",
	"build",
	"out",
	"target",
	"coverage",
	".next",
]);

const testSegments = new Set([
	"test",
	"tests",
	"__tests__",
	"spec",
	"specs",
]);

const fixtureSegments = new Set([
	"fixture",
	"fixtures",
	"snapshot",
	"snapshots",
	"golden",
	"corpus",
	"corpora",
	"mock",
	"mocks",
	"stub",
	"stubs",
]);

const documentationSegments = new Set(["doc", "docs", "documentation"]);

const exampleSegments = new Set([
	"example",
	"examples",
	"sample",
	"samples",
	"demo",
	"demos",
	"benchmark",
	"benchmarks",
	"bench",
	"benches",
]);

const configurationNames = new Set([
	"cmakelists.txt",
	"makefile",
	"gnumakefile",
	"meson.build",
	"configure",
	"configure.ac",
	"package.json",
	"package-lock.json",
	"pnpm-lock.yaml",
	"yarn.lock",
	"cargo.toml",
	"cargo.lock",
	"go.mod",
	"go.sum",
	"tsconfig.json",
	"jsconfig.json",
	"dockerfile",
	"docker-compose.yml",
	"docker-compose.yaml",
]);

const lowValueModulePatterns: Array<{
	category: FileScopeCategory;
	reason: string;
	pattern: RegExp;
}> = [
	{
		category: "test",
		reason: "test or harness module",
		pattern: /\b(test|tests|harness|harnesses|fixture|fixtures|mock|mocks)\b/i,
	},
	{
		category: "example",
		reason: "example, sample, demo, or benchmark module",
		pattern: /\b(example|examples|sample|samples|demo|demos|benchmark|benchmarks)\b/i,
	},
	{
		category: "configuration",
		reason: "build, package, CI, release, or configuration module",
		pattern:
			/\b(build|package|packaging|configuration|config|ci|release|installer)\b/i,
	},
	{
		category: "documentation",
		reason: "documentation module",
		pattern: /\b(doc|docs|documentation)\b/i,
	},
];

const normalizePath = (path: string) =>
	path.trim().replace(/\\/g, "/").replace(/^\.?\//, "").replace(/^\/+/, "");

const extensionOf = (path: string) => {
	const basename = path.split("/").pop()?.toLowerCase() || "";
	const dotIndex = basename.lastIndexOf(".");
	if (dotIndex <= 0) return "";
	return basename.slice(dotIndex);
};

const hasGlob = (path: string) => /[*?[]/.test(path);

export const classifyRuleModuleScope = (input: {
	name: string;
	summary?: string | null;
	runtimeComponents?: string[] | null;
}): ModuleScopeClassification => {
	const text = [
		input.name,
		input.summary || "",
		...(input.runtimeComponents || []),
	].join("\n");
	for (const rule of lowValueModulePatterns) {
		if (rule.pattern.test(text)) {
			return {
				category: rule.category,
				action: "exclude",
				reason: rule.reason,
			};
		}
	}
	return {
		category: "runtime-code",
		action: "include",
		reason: "runtime module",
	};
};

export const classifyRuleFileScope = (
	inputPath: string | null | undefined,
): FileScopeClassification => {
	const path = normalizePath(inputPath || "");
	if (!path || path.startsWith("..")) {
		return {
			path,
			category: "unknown",
			action: "exclude",
			reason: "empty or unsafe path",
		};
	}

	const lowerPath = path.toLowerCase();
	const basename = lowerPath.split("/").pop() || lowerPath;
	const segments = lowerPath.split("/").filter(Boolean);
	if (basename.startsWith(".")) {
		return {
			path,
			category: "configuration",
			action: "exclude",
			reason: "hidden repository metadata or dotfile configuration path",
		};
	}

	if (segments.some((segment) => generatedSegments.has(segment))) {
		return {
			path,
			category:
				segments.includes("vendor") ||
				segments.includes("third_party") ||
				segments.includes("third-party")
					? "vendor"
					: "generated",
			action: "exclude",
			reason: "generated, vendored, dependency, or build-output path",
		};
	}
	if (segments.some((segment) => fixtureSegments.has(segment))) {
		return {
			path,
			category: "fixture",
			action: "exclude",
			reason: "fixture, snapshot, corpus, mock, or stub path",
		};
	}
	if (segments.some((segment) => testSegments.has(segment))) {
		return {
			path,
			category: "test",
			action: "exclude",
			reason: "test-only path",
		};
	}
	if (segments.some((segment) => documentationSegments.has(segment))) {
		return {
			path,
			category: "documentation",
			action: "exclude",
			reason: "documentation-only path",
		};
	}
	if (segments.some((segment) => exampleSegments.has(segment))) {
		return {
			path,
			category: "example",
			action: "exclude",
			reason: "example, sample, demo, or benchmark path",
		};
	}

	const extension = extensionOf(lowerPath);
	if (configurationNames.has(basename) || configurationExtensions.has(extension)) {
		return {
			path,
			category: "configuration",
			action: "exclude",
			reason: "configuration or build metadata path",
		};
	}
	if (/^dockerfile[.-]/.test(basename)) {
		return {
			path,
			category: "configuration",
			action: "exclude",
			reason: "container build configuration path",
		};
	}
	if (segments.includes("tools") && /^(gen|generate)[-_]/.test(basename)) {
		return {
			path,
			category: "configuration",
			action: "exclude",
			reason: "build-support generator tooling path",
		};
	}
	if (documentationExtensions.has(extension)) {
		return {
			path,
			category: "documentation",
			action: "exclude",
			reason: "documentation file",
		};
	}
	if (assetExtensions.has(extension)) {
		return {
			path,
			category: "asset",
			action: "exclude",
			reason: "static asset, binary, archive, source map, or sample secret file",
		};
	}
	if (codeExtensions.has(extension) || (!extension && !hasGlob(path))) {
		return {
			path,
			category: "runtime-code",
			action: "include",
			reason: "runtime source path",
		};
	}
	if (hasGlob(path)) {
		return {
			path,
			category: "unknown",
			action: "include",
			reason: "glob scope without low-value path signals",
		};
	}
	return {
		path,
		category: "unknown",
		action: "exclude",
		reason: "unknown non-source file type",
	};
};

export const filterValuableRuleFileScopes = (scopes: string[]) => {
	const classifications = scopes.map(classifyRuleFileScope);
	return {
		includedScopes: classifications
			.filter((classification) => classification.action === "include")
			.map((classification) => classification.path),
		excludedScopes: classifications.filter(
			(classification) => classification.action === "exclude",
		),
		classifications,
	};
};
